version: 2
stages:
  build:
    machine: true
    working_directory: ~/go/src/github.com/drud/elysium

    environment:
      GOPATH: /home/circleci/go

    steps:
      - run: mkdir -p ~/go/lib && mkdir ~/go/pkg && mkdir -p ~/go/src/github.com/drud/elysium
      - checkout
      - run: make test
      - run: make -s gofmt golint

